In [1]:
import random
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

#### 1. Consider iris dataset, classify into binary classes using SVM. Report the confusion matrix and hence calculate accuracy, precision and recall for various SVM parameters and kernel functions (Linear, RBF, Polynomial).

In [2]:
iris = datasets.load_iris()

In [3]:
ind = 0
for i in iris.target:
    if i == 2:
        break
    ind += 1
        
iris.target = iris.target[:ind]
iris.data = iris.data[:ind]

In [4]:
X = iris.data
y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [5]:
svm = SVC(kernel="rbf", gamma="auto")
svm.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [6]:
svm.predict(X_test)

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1])

In [7]:
predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 10]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


In [8]:
svm = SVC(kernel="linear", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 10]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


In [9]:
svm = SVC(kernel="poly", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 10]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


#### 2. Consider iris dataset and perform classification using non-linear SVM for multi-class and report the confusion matrix and hence calculate accuracy, precision and recall (consider one-vs-all) for various SVM parameters and kernel functions (Linear, RBF, Polynomial).


##### 0 vs all

In [10]:
iris = datasets.load_iris()

iris.target = np.where((iris.target != 0), 1, 0)
        
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
X = iris.data
y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [12]:
svm = SVC(kernel="linear", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 20]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


In [13]:
svm = SVC(kernel="rbf", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 20]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


In [14]:
svm = SVC(kernel="poly", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[10  0]
 [ 0 20]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


##### 1 vs all

In [15]:
iris = datasets.load_iris()

iris.target = np.where((iris.target != 1), 0, 1)
        
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
X = iris.data
y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [17]:
svm = SVC(kernel="linear", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[17  0]
 [ 8  5]]

Accuracy:  0.7333333333333333

Precision:  1.0

Recall:  0.38461538461538464


In [18]:
svm = SVC(kernel="rbf", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[16  1]
 [ 0 13]]

Accuracy:  0.9666666666666667

Precision:  0.9285714285714286

Recall:  1.0


In [19]:
svm = SVC(kernel="poly", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[17  0]
 [ 0 13]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


##### 2 vs all

In [20]:
iris = datasets.load_iris()

iris.target = np.where((iris.target != 2), 1, 2)
        
iris.target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
X = iris.data
y = iris.target

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [22]:
svm = SVC(kernel="linear", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[18  1]
 [ 0 11]]

Accuracy:  0.9666666666666667

Precision:  1.0

Recall:  0.9473684210526315


In [23]:
svm = SVC(kernel="rbf", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[19  0]
 [ 0 11]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


In [24]:
svm = SVC(kernel="poly", gamma="auto")
svm.fit(X_train, Y_train)

predictions = svm.predict(X_test)

print("Confusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

Confusion matrix: 
 [[19  0]
 [ 0 11]]

Accuracy:  1.0

Precision:  1.0

Recall:  1.0


#### 3. Considering the Unified Learning Rule, design a perceptron network to implement the following logic functions. (Your programs must be generalized, so that it can handle any input.)
(a) AND
(b) OR
(c) NAND
(d) NOR

In [41]:
class PerceptronNetwork:
    def __init__(self, input_size):
        self.weights = [random.random() for _ in range(input_size)]
        self.bias = 0.0
    
    def predict(self, inputs):
        sum = 0.0
        for i in range(len(inputs)):
            sum += inputs[i] * self.weights[i]
        sum += self.bias
        return 1 if sum >= 0.0 else 0
    
    def train(self, inputs, output):
        prediction = self.predict(inputs)
        error = output - prediction
        for i in range(len(inputs)):
            self.weights[i] += error * inputs[i]
        self.bias += error
    
    def test(self, inputs, output):
        prediction = self.predict(inputs)
        if prediction == output:
            return True
        else:
            return False
    
    def testAll(self, inputs, outputs):
        correct = 0
        for i in range(len(inputs)):
            if self.test(inputs[i], outputs[i]):
                correct += 1
        return correct / len(inputs)
    
    def trainAll(self, inputs, outputs, epochs):
        for i in range(epochs):
            for j in range(len(inputs)):
                self.train(inputs[j], outputs[j])

inputs1 = [[0,0], [0,1], [1,0], [1,1]]
inputs2 = [[0,0], [0,1], [1,0], [1,1]]
inputs3 = [[0,0], [0,1], [1,0], [1,1]]
inputs4 = [[0,0], [0,1], [1,0], [1,1]]

output1 = [0,0,0,1]
output2 = [0,1,1,1]
output3 = [1,1,1,0]
output4 = [1,0,0,0]

p1 = PerceptronNetwork(2)
p2 = PerceptronNetwork(2)
p3 = PerceptronNetwork(2)
p4 = PerceptronNetwork(2)

p1.trainAll(inputs1, output1, 10000)
print(f'Bias: {p1.bias}, Weights: {p1.weights}')

p2.trainAll(inputs2, output2, 10000)
print(f'Bias: {p2.bias}, Weights: {p2.weights}')

p3.trainAll(inputs3, output3, 10000)
print(f'Bias: {p3.bias}, Weights: {p3.weights}')

p4.trainAll(inputs4, output4, 10000)
print(f'Bias: {p4.bias}, Weights: {p4.weights}')

Bias: -3.0, Weights: [2.2297747181283216, 1.4486816064340728]
Bias: -1.0, Weights: [1.4637005249055823, 1.800555468034211]
Bias: 2.0, Weights: [-1.760225783537947, -0.8278030762678175]
Bias: 0.0, Weights: [-0.04994917526063425, -0.04458243773048809]


In [42]:
print(p1.predict([0,1]),p2.predict([0,1]),p3.predict([0,1]),p4.predict([0,1]))

0 1 1 0
