In [38]:
from sklearn.datasets import make_moons, make_circles
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score

In [4]:
import math
from random import seed
from random import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
type(make_moons)

function

In [21]:
print(len(make_moons()[-1]))
print(len(make_moons()[0]))

100
100


In [27]:
make_moons()[0]

array([[-9.60230259e-02,  9.95379113e-01],
       [ 9.49055747e-01,  3.15108218e-01],
       [ 9.26916757e-01,  3.75267005e-01],
       [ 1.76144596e+00, -1.48228395e-01],
       [-9.97945393e-01,  6.40702200e-02],
       [ 5.18392568e-01,  8.55142763e-01],
       [ 2.00000000e+00,  5.00000000e-01],
       [ 1.51839257e+00, -3.55142763e-01],
       [ 1.34536505e+00, -4.38468422e-01],
       [ 5.72116660e-01,  8.20172255e-01],
       [ 9.91790014e-01,  1.27877162e-01],
       [ 1.00000000e+00,  0.00000000e+00],
       [ 4.27883340e-01, -3.20172255e-01],
       [-9.91790014e-01,  1.27877162e-01],
       [ 7.77479066e-01, -4.74927912e-01],
       [ 4.04783343e-01,  9.14412623e-01],
       [ 1.59599895e-01,  9.87181783e-01],
       [-6.23489802e-01,  7.81831482e-01],
       [-4.04783343e-01,  9.14412623e-01],
       [ 1.98155916e+00,  3.08841371e-01],
       [ 1.90096887e+00,  6.61162609e-02],
       [ 3.20515776e-02,  9.99486216e-01],
       [ 1.67230089e+00, -2.40277997e-01],
       [-9.

In [26]:
make_moons()[-1]

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [19]:
dataset

[[-0.0960230259, 0.995379113, 1],
 [0.949055747, 0.315108218, 1],
 [0.926916757, 0.375267005, 1],
 [1.76144596, -0.148228395, 0],
 [-0.997945393, 0.06407022, 0],
 [0.518392568, 0.855142763, 1],
 [2.0, 0.5, 0],
 [1.51839257, -0.355142763, 0],
 [1.34536505, -0.438468422, 0],
 [0.57211666, 0.820172255, 1],
 [0.991790014, 0.127877162, 1],
 [1.0, 0.0, 1],
 [0.42788334, -0.320172255, 1],
 [-0.991790014, 0.127877162, 0],
 [0.777479066, -0.474927912, 0],
 [0.404783343, 0.914412623, 0],
 [0.159599895, 0.987181783, 1],
 [-0.623489802, 0.781831482, 1],
 [-0.404783343, 0.914412623, 0],
 [1.98155916, 0.308841371, 0],
 [1.90096887, 0.0661162609, 0],
 [0.0320515776, 0.999486216, 0],
 [1.67230089, -0.240277997, 0],
 [-0.967294863, 0.253654584, 0],
 [0.00820998618, 0.372122838, 1],
 [1.8380881, -0.0455349012, 0],
 [1.96729486, 0.246345416, 0],
 [0.761445958, 0.648228395, 1],
 [1.03205158, -0.499486216, 0],
 [-0.761445958, 0.648228395, 0],
 [0.481607432, -0.355142763, 1],
 [0.53746171, -0.386599306, 0],

In [30]:
data = [[-9.60230259e-02,  9.95379113e-01],
       [ 9.49055747e-01,  3.15108218e-01],
       [ 9.26916757e-01,  3.75267005e-01],
       [ 1.76144596e+00, -1.48228395e-01],
       [-9.97945393e-01,  6.40702200e-02],
       [ 5.18392568e-01,  8.55142763e-01],
       [ 2.00000000e+00,  5.00000000e-01],
       [ 1.51839257e+00, -3.55142763e-01],
       [ 1.34536505e+00, -4.38468422e-01],
       [ 5.72116660e-01,  8.20172255e-01],
       [ 9.91790014e-01,  1.27877162e-01],
       [ 1.00000000e+00,  0.00000000e+00],
       [ 4.27883340e-01, -3.20172255e-01],
       [-9.91790014e-01,  1.27877162e-01],
       [ 7.77479066e-01, -4.74927912e-01],
       [ 4.04783343e-01,  9.14412623e-01],
       [ 1.59599895e-01,  9.87181783e-01],
       [-6.23489802e-01,  7.81831482e-01],
       [-4.04783343e-01,  9.14412623e-01],
       [ 1.98155916e+00,  3.08841371e-01],
       [ 1.90096887e+00,  6.61162609e-02],
       [ 3.20515776e-02,  9.99486216e-01],
       [ 1.67230089e+00, -2.40277997e-01],
       [-9.67294863e-01,  2.53654584e-01],
       [ 8.20998618e-03,  3.72122838e-01],
       [ 1.83808810e+00, -4.55349012e-02],
       [ 1.96729486e+00,  2.46345416e-01],
       [ 7.61445958e-01,  6.48228395e-01],
       [ 1.03205158e+00, -4.99486216e-01],
       [-7.61445958e-01,  6.48228395e-01],
       [ 4.81607432e-01, -3.55142763e-01],
       [ 5.37461710e-01, -3.86599306e-01],
       [ 6.72300890e-01,  7.40277997e-01],
       [ 1.99794539e+00,  4.35929780e-01],
       [-8.38088105e-01,  5.45534901e-01],
       [ 7.15472413e-01, -4.58667853e-01],
       [-7.18349350e-01,  6.95682551e-01],
       [ 1.92691676e+00,  1.24732995e-01],
       [-5.72116660e-01,  8.20172255e-01],
       [ 1.80141362e+00, -9.81105305e-02],
       [ 9.67294863e-01,  2.53654584e-01],
       [ 9.90311321e-02,  6.61162609e-02],
       [ 3.27699110e-01, -2.40277997e-01],
       [ 1.28452759e+00, -4.58667853e-01],
       [ 9.00968868e-01,  4.33883739e-01],
       [ 7.18349350e-01,  6.95682551e-01],
       [ 2.05460725e-03,  4.35929780e-01],
       [-9.81559157e-01,  1.91158629e-01],
       [ 2.81650650e-01, -1.95682551e-01],
       [-1.00000000e+00,  1.22464680e-16],
       [ 1.40478334e+00, -4.14412623e-01],
       [ 1.62348980e+00, -2.81831482e-01],
       [ 1.94905575e+00,  1.84891782e-01],
       [ 1.28681296e-01,  9.28244800e-03],
       [ 1.71834935e+00, -1.95682551e-01],
       [-3.20515776e-02,  9.99486216e-01],
       [-5.18392568e-01,  8.55142763e-01],
       [ 1.87131870e+00,  9.28244800e-03],
       [ 8.40400105e-01, -4.87181783e-01],
       [ 1.99179001e+00,  3.72122838e-01],
       [ 1.98586378e-01, -9.81105305e-02],
       [ 9.60230259e-02,  9.95379113e-01],
       [-9.00968868e-01,  4.33883739e-01],
       [ 0.00000000e+00,  5.00000000e-01],
       [-2.84527587e-01,  9.58667853e-01],
       [-6.72300890e-01,  7.40277997e-01],
       [ 1.09602303e+00, -4.95379113e-01],
       [ 2.22520934e-01,  9.74927912e-01],
       [ 1.15959990e+00, -4.87181783e-01],
       [-9.26916757e-01,  3.75267005e-01],
       [ 2.84527587e-01,  9.58667853e-01],
       [ 2.38554042e-01, -1.48228395e-01],
       [ 4.62538290e-01,  8.86599306e-01],
       [ 6.54634946e-01, -4.38468422e-01],
       [ 5.09442530e-02,  1.84891782e-01],
       [-1.59599895e-01,  9.87181783e-01],
       [ 3.76510198e-01, -2.81831482e-01],
       [ 7.30832427e-02,  1.24732995e-01],
       [ 9.03976974e-01, -4.95379113e-01],
       [ 8.71318704e-01,  4.90717552e-01],
       [ 5.95216657e-01, -4.14412623e-01],
       [ 9.81559157e-01,  1.91158629e-01],
       [ 3.27051370e-02,  2.46345416e-01],
       [ 1.46253829e+00, -3.86599306e-01],
       [ 1.84408430e-02,  3.08841371e-01],
       [ 1.57211666e+00, -3.20172255e-01],
       [ 9.97945393e-01,  6.40702200e-02],
       [-4.62538290e-01,  8.86599306e-01],
       [-3.45365054e-01,  9.38468422e-01],
       [-2.22520934e-01,  9.74927912e-01],
       [ 3.45365054e-01,  9.38468422e-01],
       [ 8.38088105e-01,  5.45534901e-01],
       [-8.71318704e-01,  4.90717552e-01],
       [ 8.01413622e-01,  5.98110530e-01],
       [ 1.61911895e-01, -4.55349012e-02],
       [ 1.22252093e+00, -4.74927912e-01],
       [-9.49055747e-01,  3.15108218e-01],
       [ 6.23489802e-01,  7.81831482e-01],
       [ 9.67948422e-01, -4.99486216e-01],
       [-8.01413622e-01,  5.98110530e-01]]

target = [1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0]

dataset = []
for i in range(100):
    data[i].append(target[i])
    dataset.append(data[i])

In [41]:
# Initialize a network
def initialize_network(n_inputs, n_hidden, n_outputs):
    network = list()
    hidden_layer = [{'weights':[random() for i in range(n_inputs + 1)]} for i in range(n_hidden)]
    network.append(hidden_layer)
    output_layer = [{'weights':[random() for i in range(n_hidden + 1)]} for i in range(n_outputs)]
    network.append(output_layer)
    return network

# Calculate neuron activation for an input
def activate(weights, inputs):
    activation = weights[-1]
    for i in range(len(weights)-1):
        activation += weights[i] * inputs[i]
    
    # ReLu function
    if activation > 0:
        return activation
    else:
        return 0

def feed_forward(network, row):
    inputs = row
    for layer in network:
        new_inputs = []
        for neuron in layer:
            neuron['output'] = activate(neuron['weights'], inputs)
            new_inputs.append(neuron['output'])
        inputs = new_inputs            
    return inputs

def derivative(output):
    if(output > 0):
        return 1
    else:
        return 0
    
def propagate_backward(network, expected):
    # starting backward
    for i in reversed(range(len(network))):
        layer = network[i]
        errors = list()
        if i != len(network)-1:
            for j in range(len(layer)):
                error = 0.0
                for neuron in network[i + 1]:
                    error += (neuron['weights'][j] * neuron['delta'])
                errors.append(error)
        else:
            for j in range(len(layer)):
                neuron = layer[j]
                errors.append(neuron['output'] - expected[j])
        for j in range(len(layer)):
            neuron = layer[j]
            neuron['delta'] = errors[j] * derivative(neuron['output'])
            
# Update network weights with error
def update_weights(network, row, l_rate):
    for i in range(len(network)):
        inputs = row[:-1]
        if i != 0:
            inputs = [neuron['output'] for neuron in network[i - 1]]
        for neuron in network[i]:
            for j in range(len(inputs)):
                neuron['weights'][j] -= l_rate * neuron['delta'] * inputs[j]
            neuron['weights'][-1] -= l_rate * neuron['delta']
            
# Train a network for a fixed number of epochs
def train_network(network, train, l_rate, n_epoch, n_outputs):
    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            outputs = feed_forward(network, row)
            expected = [0 for i in range(n_outputs)]
            expected[row[-1]] = 1
            sum_error += sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
            propagate_backward(network, expected)
            update_weights(network, row, l_rate)
        print('epoch=%d, error=%.3f' % (epoch, sum_error))
        
        
# Make a prediction with a network
def predict(network, row):
    outputs = feed_forward(network, row)
    return outputs.index(max(outputs))

seed(1)

n_inputs = len(dataset[0]) - 1
n_outputs = len(set([row[-1] for row in dataset]))
n_hidden = 2

network = initialize_network(n_inputs, n_hidden, n_outputs)
train_network(network, dataset[:50], 0.5, 20, n_outputs)
for layer in network:
    print("\n")
    print(layer)
    
predictions = []
for row in dataset[50:]:
    prediction = predict(network, row)
    predictions.append(prediction)
    
Y_test = target[50:]
print("\nConfusion matrix: \n", confusion_matrix(Y_test, predictions))
print("\nAccuracy score: ", accuracy_score(Y_test, predictions))
print("\nPrecision: ", precision_score(Y_test, predictions))
print("\nRecall: ", recall_score(Y_test, predictions))

epoch=0, error=46.020
epoch=1, error=41.672
epoch=2, error=41.670
epoch=3, error=41.670
epoch=4, error=41.669
epoch=5, error=41.668
epoch=6, error=41.669
epoch=7, error=41.669
epoch=8, error=41.669
epoch=9, error=41.669
epoch=10, error=41.669
epoch=11, error=41.669
epoch=12, error=41.669
epoch=13, error=41.669
epoch=14, error=41.669
epoch=15, error=41.669
epoch=16, error=41.669
epoch=17, error=41.669
epoch=18, error=41.669
epoch=19, error=41.669


[{'weights': [0.06175407167642487, 0.029300516880571507, -0.1494748032077816], 'output': 0, 'delta': 0.0}, {'weights': [-0.3279459640893158, -0.27970987536439007, -0.7618139414236436], 'output': 0, 'delta': -0.0}]


[{'weights': [-0.8287307654361826, -0.06373462093231108, -0.8345979221334394], 'output': 0, 'delta': 0}, {'weights': [-0.024844352691528966, 0.5904351338538281, 0.8892184646752311], 'output': 0.7784369293504623, 'delta': -0.22156307064953773}]

Confusion matrix: 
 [[ 0 24]
 [ 0 26]]

Accuracy score:  0.52

Precision:  0.52

Recall